# Generated by Django 3.1.5 on 2021-01-05 07:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('street', models.CharField(max_length=50)),
                ('building_number', models.SmallIntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='restaurant name')),
                ('brief', models.TextField(blank=True, verbose_name='brief about the restaurant')),
                ('delivery', models.BooleanField(default=False)),
                ('Takeout', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_rating.location', verbose_name='restaurant location')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('score', models.IntegerField(choices=[(1, 'very poor'), (2, 'poor'), (3, 'fair'), (4, 'good'), (5, 'excellent')], default=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_rating.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
